version: "3.8"
services:
  globalping-api:
    image: jimaek/globalping-api:latest
    stop_grace_period: 30s
    stop_signal: SIGTERM
    deploy:
      mode: global
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
      restart_policy:
        condition: any
        delay: 3s
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - globalping.env
 #logging enables log stream to systemd for newrelic agent to read. To enable create /etc/newrelic-infra/logging.d/systemd.yml with content https://gist.github.com/jimaek/14dfee57b982bd2344ad586a87c6526f
    logging:
      driver: journald
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/v1/probes"]
      interval: 6s
      timeout: 6s
      retries: 2
      start_period: 3s
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: ingress
