export const states: Record<string, string> = {
	'Alabama': 'AL',
	'Alaska': 'AK',
	'American Samoa': 'AS',
	'Arizona': 'AZ',
	'Arkansas': 'AR',
	'California': 'CA',
	'Colorado': 'CO',
	'Connecticut': 'CT',
	'Delaware': 'DE',
	'Washington, D.C.': 'DC',
	'District of Columbia': 'DC',
	'Florida': 'FL',
	'Georgia': 'GA',
	'Guam': 'GU',
	'Hawaii': 'HI',
	'Idaho': 'ID',
	'Illinois': 'IL',
	'Indiana': 'IN',
	'Iowa': 'IA',
	'Kansas': 'KS',
	'Kentucky': 'KY',
	'Louisiana': 'LA',
	'Maine': 'ME',
	'Marshall Islands': 'MH',
	'Maryland': 'MD',
	'Massachusetts': 'MA',
	'Michigan': 'MI',
	'Minnesota': 'MN',
	'Mississippi': 'MS',
	'Missouri': 'MO',
	'Montana': 'MT',
	'Nebraska': 'NE',
	'Nevada': 'NV',
	'New Hampshire': 'NH',
	'New Jersey': 'NJ',
	'New Mexico': 'NM',
	'New York': 'NY',
	'North Carolina': 'NC',
	'North Dakota': 'ND',
	'Northern Mariana Islands': 'MP',
	'Ohio': 'OH',
	'Oklahoma': 'OK',
	'Oregon': 'OR',
	'Palau': 'PW',
	'Pennsylvania': 'PA',
	'Puerto Rico': 'PR',
	'Rhode Island': 'RI',
	'South Carolina': 'SC',
	'South Dakota': 'SD',
	'Tennessee': 'TN',
	'Texas': 'TX',
	'Utah': 'UT',
	'Vermont': 'VT',
	'Virgin Islands': 'VI',
	'Virginia': 'VA',
	'Washington': 'WA',
	'West Virginia': 'WV',
	'Wisconsin': 'WI',
	'Wyoming': 'WY',
};

export const statesIso: Record<string, string> = {
	AL: 'US-AL',
	AK: 'US-AK',
	AS: 'US-AS',
	AZ: 'US-AZ',
	AR: 'US-AR',
	CA: 'US-CA',
	CO: 'US-CO',
	CT: 'US-CT',
	DE: 'US-DE',
	DC: 'US-DC',
	FL: 'US-FL',
	GA: 'US-GA',
	GU: 'US-GU',
	HI: 'US-HI',
	ID: 'US-ID',
	IL: 'US-IL',
	IN: 'US-IN',
	IA: 'US-IA',
	KS: 'US-KS',
	KY: 'US-KY',
	LA: 'US-LA',
	ME: 'US-ME',
	MH: 'US-MH',
	MD: 'US-MD',
	MA: 'US-MA',
	MI: 'US-MI',
	MN: 'US-MN',
	MS: 'US-MS',
	MO: 'US-MO',
	MT: 'US-MT',
	NE: 'US-NE',
	NV: 'US-NV',
	NH: 'US-NH',
	NJ: 'US-NJ',
	NM: 'US-NM',
	NY: 'US-NY',
	NC: 'US-NC',
	ND: 'US-ND',
	MP: 'US-MP',
	OH: 'US-OH',
	OK: 'US-OK',
	OR: 'US-OR',
	PW: 'US-PW',
	PA: 'US-PA',
	PR: 'US-PR',
	RI: 'US-RI',
	SC: 'US-SC',
	SD: 'US-SD',
	TN: 'US-TN',
	TX: 'US-TX',
	UT: 'US-UT',
	VT: 'US-VT',
	VI: 'US-VI',
	VA: 'US-VA',
	WA: 'US-WA',
	WV: 'US-WV',
	WI: 'US-WI',
	WY: 'US-WY',
};
